set(BASE_SOURCES
    actors/archvile.txt
    actors/baby.txt
    actors/brain.txt
    actors/bruiser.txt
    actors/caco.txt
    actors/cyber.txt
    actors/demon.txt
    actors/doomdeco.txt
    actors/doomimp.txt
    actors/doommisc.txt
    actors/fatso.txt
    actors/keen.txt
    actors/lostsoul.txt
    actors/painelem.txt
    actors/possess.txt
    actors/revenant.txt
    actors/spider.txt
    colormaps/watermap.cmp
    graphics/cross00.png
    graphics/cross01.png
    graphics/cross02.png
    graphics/cross03.png
    graphics/cross04.png
    graphics/cross05.png
    graphics/cross06.png
    graphics/cross07.png
    graphics/cross08.png
    graphics/dig033.png
    graphics/dig037.png
    graphics/dig043.png
    graphics/dig045.png
    graphics/dig046.png
    graphics/dig047.png
    graphics/dig048.png
    graphics/dig049.png
    graphics/dig050.png
    graphics/dig051.png
    graphics/dig052.png
    graphics/dig053.png
    graphics/dig054.png
    graphics/dig055.png
    graphics/dig056.png
    graphics/dig057.png
    graphics/dig058.png
    graphics/dig065.png
    graphics/dig066.png
    graphics/dig067.png
    graphics/dig068.png
    graphics/dig069.png
    graphics/dig070.png
    graphics/dig071.png
    graphics/dig072.png
    graphics/dig073.png
    graphics/dig074.png
    graphics/dig075.png
    graphics/dig076.png
    graphics/dig077.png
    graphics/dig078.png
    graphics/dig079.png
    graphics/dig080.png
    graphics/dig081.png
    graphics/dig082.png
    graphics/dig083.png
    graphics/dig084.png
    graphics/dig085.png
    graphics/dig086.png
    graphics/dig087.png
    graphics/dig088.png
    graphics/dig089.png
    graphics/dig090.png
    graphics/dig091.png
    graphics/dig093.png

    graphics/smbfgg0.png
    graphics/smbfgg1.png
    graphics/smcsaw0.png
    graphics/smcsaw1.png
    graphics/smfist0.png
    graphics/smfist1.png
    graphics/smlaun0.png
    graphics/smlaun1.png
    graphics/smmgun0.png
    graphics/smmgun1.png
    graphics/smpisg0.png
    graphics/smpisg1.png
    graphics/smplas0.png
    graphics/smplas1.png
    graphics/smsgn20.png
    graphics/smsgn21.png
    graphics/smshot0.png
    graphics/smshot1.png
    graphics/smunkn0.png
    graphics/smunkn1.png

    graphics/stbr123.png
    graphics/stbr124.png
    graphics/stbr125.png
    graphics/stbr126.png
    graphics/stbr127.png
    graphics/stkeys6.png
    graphics/stkeys7.png
    graphics/stkeys8.png

    graphics/m_butt1.png
    graphics/m_butt2.png
    graphics/m_vbox.png

    sounds/dsdgact.wav
    sounds/dsdgatk.wav
    sounds/dsdgdth.wav
    sounds/dsdgpain.wav
    sounds/dsdgsit.wav

    sprites/bon3a0.png
    sprites/bon4a0.png
    sprites/dogsa1.png
    sprites/dogsa2.png
    sprites/dogsa3.png
    sprites/dogsa4.png
    sprites/dogsa5.png
    sprites/dogsa6.png
    sprites/dogsa7.png
    sprites/dogsa8.png
    sprites/dogsb1.png
    sprites/dogsb2.png
    sprites/dogsb3.png
    sprites/dogsb4.png
    sprites/dogsb5.png
    sprites/dogsb6.png
    sprites/dogsb7.png
    sprites/dogsb8.png
    sprites/dogsc1.png
    sprites/dogsc2.png
    sprites/dogsc3.png
    sprites/dogsc4.png
    sprites/dogsc5.png
    sprites/dogsc6.png
    sprites/dogsc7.png
    sprites/dogsc8.png
    sprites/dogsd1.png
    sprites/dogsd2.png
    sprites/dogsd3.png
    sprites/dogsd4.png
    sprites/dogsd5.png
    sprites/dogsd6.png
    sprites/dogsd7.png
    sprites/dogsd8.png
    sprites/dogse1.png
    sprites/dogse2.png
    sprites/dogse3.png
    sprites/dogse4.png
    sprites/dogse5.png
    sprites/dogse6.png
    sprites/dogse7.png
    sprites/dogse8.png
    sprites/dogsf1.png
    sprites/dogsf2.png
    sprites/dogsf3.png
    sprites/dogsf4.png
    sprites/dogsf5.png
    sprites/dogsf6.png
    sprites/dogsf7.png
    sprites/dogsf8.png
    sprites/dogsg1.png
    sprites/dogsg2.png
    sprites/dogsg3.png
    sprites/dogsg4.png
    sprites/dogsg5.png
    sprites/dogsg6.png
    sprites/dogsg7.png
    sprites/dogsg8.png
    sprites/dogsh1.png
    sprites/dogsh2.png
    sprites/dogsh3.png
    sprites/dogsh4.png
    sprites/dogsh5.png
    sprites/dogsh6.png
    sprites/dogsh7.png
    sprites/dogsh8.png
    sprites/dogsi0.png
    sprites/dogsj0.png
    sprites/dogsk0.png
    sprites/dogsl0.png
    sprites/dogsm0.png
    sprites/dogsn0.png
    sprites/pls1a0.png
    sprites/pls1b0.png
    sprites/pls1c0.png
    sprites/pls1d0.png
    sprites/pls1e0.png
    sprites/pls1f0.png
    sprites/pls1g0.png
    sprites/pls2a0.png
    sprites/pls2b0.png
    sprites/pls2c0.png
    sprites/pls2d0.png
    sprites/pls2e0.png
    sprites/tnt1a0.png

    animated.lmp
    amapdef.json
    chexdeh.lmp
    compdb.json
    crblack.lmp
    crblue.lmp
    crblue2.lmp
    crbrick.lmp
    crbrown.lmp
    crgold.lmp
    crgray.lmp
    crgreen.lmp
    crorange.lmp
    crpurple.lmp
    crred.lmp
    crtan.lmp
    crwhite.lmp
    cryellow.lmp
    declare.txt
    dmxopl.op2
    sbardef.json
    sbhuddef.json
    skytran.lmp
    switches.lmp

    filter/betalevl.wad/umapinfo.lmp

    filter/chex.wad/brghtmps.lmp
    filter/chex.wad/umapinfo.lmp

    filter/chex2.wad/brghtmps.lmp
    filter/chex2.wad/dehacked.lmp

    filter/chex-all/brghtmps.lmp

    filter/doom-all/brghtmps.lmp

    filter/e1m4b.wad/dehacked.lmp
    filter/e1m8b.wad/dehacked.lmp

    filter/hacx.wad/brghtmps.lmp
    filter/hacx.wad/dehacked.lmp

    filter/id1.wad/dehacked.lmp
    filter/id1.wad/smflam0.png
    filter/id1.wad/smflam1.png
    filter/id1.wad/smheat0.png
    filter/id1.wad/smheat1.png

    filter/rekkr-all/dehacked.lmp

    filter/tnt.wad/brghtmps.lmp)

add_custom_command(OUTPUT "${BASE_PK3_PATH}"
    COMMAND ${CMAKE_COMMAND} -E tar cf "${BASE_PK3_PATH}" --format=zip ${BASE_SOURCES}
    DEPENDS ${BASE_SOURCES}
    WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}")

add_custom_target(woof-base DEPENDS "${BASE_PK3_PATH}")

if(WIN32)
    install(FILES "${BASE_PK3_PATH}" DESTINATION .)
else()
    install(FILES "${BASE_PK3_PATH}" DESTINATION "share/${PROJECT_SHORTNAME}")
endif()
