//
//  Copyright (C) 1999 by
//  id Software, Chi Hoang, Lee Killough, Jim Flynn, Rand Phares, Ty Halderman
//  Copyright(C) 2015-2020 Fabian Greffrath
//
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
// DESCRIPTION:
//      support extended nodes
//
//-----------------------------------------------------------------------------

#include <math.h>
#include <string.h>

#include "doomstat.h"
#include "doomtype.h"
#include "i_printf.h"
#include "i_system.h"
#include "m_arena.h"
#include "m_argv.h"
#include "m_fixed.h"
#include "m_swap.h"
#include "p_bsp.h"
#include "p_level.h"
#include "p_setup.h"
#include "r_defs.h"
#include "r_main.h"
#include "r_state.h"
#include "w_wad.h"
#include "z_zone.h"

// [FG] support maps with NODES in compressed ZDBSP formats
#include "miniz.h"

#if defined(_MSC_VER)
  #pragma pack(push, 1)
#endif

// [FG] extended nodes
#define NF_SUBSECTOR_VANILLA 0x8000

// BSP node structure.
typedef struct PACKED_PREFIX
{
    int16_t x; // Partition line from (x,y) to x+dx,y+dy)
    int16_t y;
    int16_t dx;
    int16_t dy;
    // Bounding box for each child, clip against view frustum.
    int16_t bbox[2][4];
    // If NF_SUBSECTOR its a subsector, else it's a node of another subtree.
    uint16_t children[2];
} PACKED_SUFFIX mapnode_t;

// SubSector, as generated by BSP.
typedef struct PACKED_PREFIX
{
    uint16_t numsegs;
    // Index of first one; segs are stored sequentially.
    uint16_t firstseg;
} PACKED_SUFFIX mapsubsector_t;

// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
typedef struct PACKED_PREFIX
{
    uint16_t v1;
    uint16_t v2;
    uint16_t angle;
    uint16_t linedef;
    uint16_t side;
    uint16_t offset;
} PACKED_SUFFIX mapseg_t;

// [FG] support maps with DeePBSPV4 nodes
typedef PACKED_PREFIX struct
{
    uint32_t v1;
    uint32_t v2;
    uint16_t angle;
    uint16_t linedef;
    uint16_t side;
    uint16_t offset;
} PACKED_SUFFIX mapseg_deepbspv4_t;

typedef PACKED_PREFIX struct
{
    int16_t x;
    int16_t y;
    int16_t dx;
    int16_t dy;
    int16_t bbox[2][4];
    uint32_t children[2];
} PACKED_SUFFIX mapnode_deepbspv4_t;

typedef PACKED_PREFIX struct
{
    uint16_t numsegs;
    uint32_t firstseg;
} PACKED_SUFFIX mapsubsector_deepbspv4_t;

// [FG] support maps with ZDBSP nodes
typedef PACKED_PREFIX struct
{
    uint32_t v1, v2;
    uint16_t linedef;
    uint8_t side;
} PACKED_SUFFIX mapseg_xnod_t;

typedef PACKED_PREFIX struct
{
    int16_t x;
    int16_t y;
    int16_t dx;
    int16_t dy;
    int16_t bbox[2][4];
    uint32_t children[2];
} PACKED_SUFFIX mapnode_xnod_t;

typedef PACKED_PREFIX struct
{
    uint32_t numsegs;
} PACKED_SUFFIX mapsubsector_xnod_t;

typedef PACKED_PREFIX struct
{
    uint32_t vertex, partner;
    uint16_t linedef;
    uint8_t side;
} PACKED_SUFFIX mapseg_xgln_t;

typedef PACKED_PREFIX struct
{
    uint32_t vertex, partner;
    uint32_t linedef;
    uint8_t side;
} PACKED_SUFFIX mapseg_xgl2_t;

typedef PACKED_PREFIX struct
{
    fixed_t x;
    fixed_t y;
    fixed_t dx;
    fixed_t dy;
    uint16_t bbox[2][4];
    uint32_t children[2];
} PACKED_SUFFIX mapnode_xgl3_t;

#if defined(_MSC_VER)
  #pragma pack(pop)
#endif

void P_InitSubsectorLines(void)
{
    size_t count = 0;

    if (sslines_indexes)
    {
        free(sslines_indexes);
        sslines_indexes = NULL;
    }

    if (sslines)
    {
        free(sslines);
        sslines = NULL;
    }

    sslines_indexes = malloc((numsubsectors + 1) * sizeof(sslines_indexes[0]));

    for (size_t num = 0; num < numsubsectors; num++)
    {
        size_t first_line = subsectors[num].firstline;
        size_t last_line = first_line + subsectors[num].numlines;
        seg_t *seg_last = &segs[last_line];

        sslines_indexes[num] = count;

        for (seg_t *seg = &segs[first_line]; seg < seg_last; seg++)
        {
            if (!seg->linedef)
            {
                continue;
            }
            seg->linedef->validcount = 0;
        }

        for (seg_t *seg = &segs[first_line]; seg < seg_last; seg++)
        {
            if (!seg->linedef)
            {
                continue;
            }

            if (seg->linedef->validcount == 1)
            {
                continue;
            }

            seg->linedef->validcount = 1;
            count++;
        }
    }

    sslines_indexes[numsubsectors] = count;

    sslines = malloc(count * sizeof(sslines[0]));
    count = 0;

    for (size_t num = 0; num < numsubsectors; num++)
    {
        size_t first_line = subsectors[num].firstline;
        size_t last_line = first_line + subsectors[num].numlines;
        seg_t *seg_last = &segs[last_line];

        for (seg_t *seg = &segs[first_line]; seg < seg_last; seg++)
        {
            if (!seg->linedef)
            {
                continue;
            }
            seg->linedef->validcount = 0;
        }

        for (seg_t *seg = &segs[first_line]; seg < seg_last; seg++)
        {
            ssline_t *ssline = &sslines[count];
            if (!seg->linedef)
            {
                continue;
            }

            if (seg->linedef->validcount == 1)
            {
                continue;
            }

            seg->linedef->validcount = 1;

            ssline->seg = seg;
            ssline->linedef = seg->linedef;

            ssline->x1 = seg->linedef->v1->x;
            ssline->y1 = seg->linedef->v1->y;
            ssline->x2 = seg->linedef->v2->x;
            ssline->y2 = seg->linedef->v2->y;
            ssline->bbox[0] = seg->linedef->bbox[0];
            ssline->bbox[1] = seg->linedef->bbox[1];
            ssline->bbox[2] = seg->linedef->bbox[2];
            ssline->bbox[3] = seg->linedef->bbox[3];

            count++;
        }
    }

    for (size_t num = 0; num < numlines; num++)
    {
        lines[num].validcount = 0;
    }
}

// [FG] support extended nodes

void P_CheckBSPFormat_Binary(map_t *map)
{
    map->bsp_format = BSP_DOOMBSP;
    int size_subs = 0, size_nodes = 0;

    //!
    // @category mod
    //
    // Forces rebuilding of nodes.
    //

    if (M_CheckParm("-bsp"))
    {
        map->bsp_format = BSP_NANO;
        return;
    }

    //!
    // @category mod
    //
    // Forces extended (non-GL) ZDoom nodes.
    //

    if (!M_CheckParm("-force_old_zdoom_nodes"))
    {
        size_subs = W_LumpLengthWithName(map->ssectors, "SSECTORS");

        if (size_subs >= sizeof(mapsubsector_t))
        {
            byte *lump_data = W_CacheLumpNum(map->ssectors, PU_STATIC);

            if (!memcmp(lump_data, "XGLN", 4))
            {
                map->bsp_format = BSP_XGLN;
                map->znodes = map->ssectors;
            }
            else if (!memcmp(lump_data, "ZGLN", 4))
            {
                map->bsp_format = BSP_ZGLN;
                map->znodes = map->ssectors;
            }
            else if (!memcmp(lump_data, "XGL2", 4))
            {
                map->bsp_format = BSP_XGL2;
                map->znodes = map->ssectors;
            }
            else if (!memcmp(lump_data, "ZGL2", 4))
            {
                map->bsp_format = BSP_ZGL2;
                map->znodes = map->ssectors;
            }
            else if (!memcmp(lump_data, "XGL3", 4))
            {
                map->bsp_format = BSP_XGL3;
                map->znodes = map->ssectors;
            }
            else if (!memcmp(lump_data, "ZGL3", 4))
            {
                map->bsp_format = BSP_ZGL3;
                map->znodes = map->ssectors;
            }

            Z_Free(lump_data);
        }
        else
        {
            map->bsp_format = BSP_NANO;
        }
    }

    if (map->bsp_format == BSP_DOOMBSP || map->bsp_format == BSP_NANO)
    {
        size_nodes = W_LumpLengthWithName(map->nodes, "NODES");

        if (size_nodes >= sizeof(mapnode_t))
        {
            byte *lump_data = W_CacheLumpNum(map->nodes, PU_STATIC);

            if (!memcmp(lump_data, "xNd4\0\0\0\0", 8))
            {
                map->bsp_format = BSP_DEEPBSPV4;
            }
            else if (!memcmp(lump_data, "XNOD", 4))
            {
                map->bsp_format = BSP_XNOD;
                map->znodes = map->nodes;
            }
            else if (!memcmp(lump_data, "ZNOD", 4))
            {
                map->bsp_format = BSP_ZNOD;
                map->znodes = map->nodes;
            }

            Z_Free(lump_data);
        }
        else
        {
            map->bsp_format = BSP_NANO;
        }
    }

    // [FG] no nodes for exactly one subsector
    if (size_subs == sizeof(mapsubsector_t) && size_nodes == 0)
    {
        map->bsp_format = BSP_DOOMBSP;
    }
}

void P_CheckBSPFormat_UDMF(map_t *map)
{
    byte *lump_data = W_CacheLumpNum(map->znodes, PU_STATIC);
    if (!memcmp(lump_data, "XNOD", 4))
    {
        map->bsp_format = BSP_XNOD;
    }
    else if (!memcmp(lump_data, "ZNOD", 4))
    {
        map->bsp_format = BSP_ZNOD;
    }
    else if (!memcmp(lump_data, "XGLN", 4))
    {
        map->bsp_format = BSP_XGLN;
    }
    else if (!memcmp(lump_data, "ZGLN", 4))
    {
        map->bsp_format = BSP_ZGLN;
    }
    else if (!memcmp(lump_data, "XGL2", 4))
    {
        map->bsp_format = BSP_XGL2;
    }
    else if (!memcmp(lump_data, "ZGL2", 4))
    {
        map->bsp_format = BSP_ZGL2;
    }
    else if (!memcmp(lump_data, "XGL3", 4))
    {
        map->bsp_format = BSP_XGL3;
    }
    else if (!memcmp(lump_data, "ZGL3", 4))
    {
        map->bsp_format = BSP_ZGL3;
    }
    Z_Free(lump_data);
}

// [FG] recalculate seg offsets

int P_GetOffset(vertex_t *v1, vertex_t *v2)
{
    float a, b;
    int r;

    a = (float)(v1->x - v2->x) / (float)FRACUNIT;
    b = (float)(v1->y - v2->y) / (float)FRACUNIT;
    r = (int)(sqrt(a * a + b * b) * (float)FRACUNIT);

    return r;
}

// [FG] extended nodes

//
// P_LoadNodes
//
// killough 5/3/98: reformatted, cleaned up

void P_LoadNodes(map_t *map)
{
    numnodes = W_LumpLength(map->nodes) / sizeof(mapnode_t);
    nodes = Z_Malloc(numnodes * sizeof(node_t), PU_LEVEL, 0);
    mapnode_t *data = W_CacheLumpNum(map->nodes, PU_STATIC);

    for (size_t i = 0; i < numnodes; i++)
    {
        node_t *no = &nodes[i];
        mapnode_t *mn = &data[i];

        no->x = IntToFixed(SHORT(mn->x));
        no->y = IntToFixed(SHORT(mn->y));
        no->dx = IntToFixed(SHORT(mn->dx));
        no->dy = IntToFixed(SHORT(mn->dy));

        for (int j = 0; j < 2; j++)
        {
            no->children[j] = USHORT(mn->children[j]);

            if (no->children[j] == NO_INDEX_SHORT)
            {
                no->children[j] = NO_INDEX;
            }
            else if (no->children[j] & NF_SUBSECTOR_VANILLA)
            {
                no->children[j] &= ~NF_SUBSECTOR_VANILLA;

                if (no->children[j] >= numsubsectors)
                {
                    no->children[j] = 0;
                }

                no->children[j] |= NF_SUBSECTOR;
            }

            for (int k = 0; k < 4; k++)
            {
                no->bbox[j][k] = IntToFixed(SHORT(mn->bbox[j][k]));
            }
        }
    }

    Z_Free(data);
}

//
// P_LoadSubsectors
//
// killough 5/3/98: reformatted, cleaned up

void P_LoadSubsectors(map_t *map)
{
    numsubsectors = W_LumpLength(map->ssectors) / sizeof(mapsubsector_t);
    subsectors = arena_alloc_num(world_arena, subsector_t, numsubsectors);
    mapsubsector_t *data = W_CacheLumpNum(map->ssectors, PU_STATIC);

    memset(subsectors, 0, numsubsectors * sizeof(subsector_t));

    for (int i = 0; i < numsubsectors; i++)
    {
        subsector_t *sss = &subsectors[i];
        mapsubsector_t *mss = &data[i];

        // [FG] extended nodes
        sss->numlines = USHORT(mss->numsegs);
        sss->firstline = USHORT(mss->firstseg);
    }

    Z_Free(data);
}

//
// P_LoadSegs
//
// killough 5/3/98: reformatted, cleaned up

void P_LoadSegs(map_t *map)
{
    numsegs = W_LumpLength(map->segs) / sizeof(mapseg_t);
    segs = arena_alloc_num(world_arena, seg_t, numsegs);
    mapseg_t *data = W_CacheLumpNum(map->segs, PU_STATIC);

    for (int i = 0; i < numsegs; i++)
    {
        seg_t *li = &segs[i];
        mapseg_t *ml = &data[i];

        unsigned int v1, v2;
        uint32_t side, linedef;
        line_t *ldef;

        // [FG] extended nodes
        v1 = USHORT(ml->v1);
        v2 = USHORT(ml->v2);

        li->angle = IntToFixed(SHORT(ml->angle));
        linedef = USHORT(ml->linedef); // [FG] extended nodes

        // Andrey Budko: check for wrong indexes
        if (linedef >= numlines)
        {
            I_Error("seg %d references a non-existent linedef %d", i, linedef);
        }

        ldef = &lines[linedef];
        li->linedef = ldef;
        side = SHORT(ml->side);

        // Andrey Budko: check for wrong indexes
        if (ldef->sidenum[side] >= numsides)
        {
            I_Error(
                "linedef %d for seg %d references a non-existent sidedef %d",
                linedef, i, ldef->sidenum[side]);
        }

        li->sidedef = &sides[ldef->sidenum[side]];

        /* cph 2006/09/30 - our frontsector can be the second side of the
         * linedef, so must check for NO_INDEX in case we are incorrectly
         * referencing the back of a 1S line */
        if (ldef->sidenum[side] != NO_INDEX)
        {
            li->frontsector = sides[ldef->sidenum[side]].sector;
        }
        else
        {
            li->frontsector = 0;
            I_Printf(VB_DEBUG, "%s: front of seg %i has no sidedef", __func__,
                     i);
        }

        if (ldef->flags & ML_TWOSIDED)
        {
            int sidenum = ldef->sidenum[side ^ 1];

            if (sidenum == NO_INDEX)
            {
                // this is wrong
                li->backsector = P_GetSectorAtNullAddress();
            }
            else
            {
                li->backsector = sides[sidenum].sector;
            }
        }
        else
        {
            li->backsector = 0;
        }

        // Andrey Budko
        // check and fix wrong references to non-existent vertexes
        // see e1m9 @ NIVELES.WAD
        // http://www.doomworld.com/idgames/index.php?id=12647
        if (v1 >= numvertexes || v2 >= numvertexes)
        {
            if (v1 >= numvertexes)
            {
                I_Printf(VB_WARNING,
                         "%s: compatibility loss - seg %d "
                         "references a non-existent vertex %d.",
                         __func__, i, v1);
            }

            if (v2 >= numvertexes)
            {
                I_Printf(VB_WARNING,
                         "%s: compatibility loss - seg %d "
                         "references a non-existent vertex %d.",
                         __func__, i, v2);
            }

            if (demorecording)
            {
                I_Error("Demo recording on levels with invalid "
                        "nodes is not allowed.");
            }

            if (li->sidedef == &sides[li->linedef->sidenum[0]])
            {
                li->v1 = lines[ml->linedef].v1;
                li->v2 = lines[ml->linedef].v2;
            }
            else
            {
                li->v1 = lines[ml->linedef].v2;
                li->v2 = lines[ml->linedef].v1;
            }
        }
        else
        {
            li->v1 = &vertexes[v1];
            li->v2 = &vertexes[v2];
        }

        // [FG] recalculate
        li->offset = P_GetOffset(li->v1, (ml->side ? ldef->v2 : ldef->v1));
    }

    Z_Free(data);
}

// [FG] support maps with DeePBSP nodes

void P_LoadSegs_DeePBSPV4(map_t *map)
{
    numsegs = W_LumpLength(map->segs) / sizeof(mapseg_deepbspv4_t);
    segs = arena_alloc_num(world_arena, seg_t, numsegs);
    mapseg_deepbspv4_t *data = W_CacheLumpNum(map->segs, PU_STATIC);

    for (int i = 0; i < numsegs; i++)
    {
        seg_t *li = &segs[i];
        mapseg_deepbspv4_t *ml = &data[i];
        int32_t side, linedef;
        line_t *ldef;
        int v1, v2;

        // [MB] 2020-04-22: Fix endianess for DeePBSPV4 nodes
        v1 = LONG(ml->v1);
        v2 = LONG(ml->v2);

        li->angle = IntToFixed(SHORT(ml->angle));

        linedef = USHORT(ml->linedef); // [FG] extended nodes

        // Andrey Budko: check for wrong indexes
        if (linedef >= numlines)
        {
            I_Error("seg %d references a non-existent linedef %d", i, linedef);
        }

        ldef = &lines[linedef];
        li->linedef = ldef;

        side = SHORT(ml->side);
        // Andrey Budko: fix wrong side index
        if (side != 0 && side != 1)
        {
            side = 1;
        }

        li->sidedef = &sides[ldef->sidenum[side]];

        /* cph 2006/09/30 - our frontsector can be the second side of the
         * linedef, so must check for NO_INDEX in case we are incorrectly
         * referencing the back of a 1S line */
        if (ldef->sidenum[side] != NO_INDEX)
        {
            li->frontsector = sides[ldef->sidenum[side]].sector;
        }
        else
        {
            li->frontsector = 0;
            I_Printf(VB_DEBUG, "%s: front of seg %i has no sidedef", __func__,
                     i);
        }

        if (ldef->flags & ML_TWOSIDED && ldef->sidenum[side ^ 1] != NO_INDEX)
        {
            li->backsector = sides[ldef->sidenum[side ^ 1]].sector;
        }
        else
        {
            li->backsector = 0;
        }

        // Andrey Budko
        // check and fix wrong references to non-existent vertexes
        // see e1m9 @ NIVELES.WAD
        // http://www.doomworld.com/idgames/index.php?id=12647
        if (v1 >= numvertexes || v2 >= numvertexes)
        {
            if (v1 >= numvertexes)
            {
                I_Printf(VB_WARNING,
                         "%s: compatibility loss - seg %d "
                         "references a non-existent vertex %d.",
                         __func__, i, v1);
            }

            if (v2 >= numvertexes)
            {
                I_Printf(VB_WARNING,
                         "%s: compatibility loss - seg %d "
                         "references a non-existent vertex %d.",
                         __func__, i, v2);
            }

            if (demorecording)
            {
                I_Error("Demo recording on levels with invalid "
                        "nodes is not allowed.");
            }

            if (li->sidedef == &sides[li->linedef->sidenum[0]])
            {
                li->v1 = lines[ml->linedef].v1;
                li->v2 = lines[ml->linedef].v2;
            }
            else
            {
                li->v1 = lines[ml->linedef].v2;
                li->v2 = lines[ml->linedef].v1;
            }
        }
        else
        {
            li->v1 = &vertexes[v1];
            li->v2 = &vertexes[v2];
        }

        // [FG] recalculate
        li->offset = P_GetOffset(li->v1, (ml->side ? ldef->v2 : ldef->v1));
    }

    Z_Free(data);
}

void P_LoadSubsectors_DeePBSPV4(map_t *map)
{
    numsubsectors =
        W_LumpLength(map->ssectors) / sizeof(mapsubsector_deepbspv4_t);
    subsectors = arena_alloc_num(world_arena, subsector_t, numsubsectors);
    mapsubsector_deepbspv4_t *data = W_CacheLumpNum(map->ssectors, PU_STATIC);

    memset(subsectors, 0, numsubsectors * sizeof(subsector_t));

    for (size_t i = 0; i < numsubsectors; i++)
    {
        subsector_t *sss = &subsectors[i];
        mapsubsector_deepbspv4_t *mss = &data[i];

        // [MB] 2020-04-22: Fix endianess for DeePBSPV4 nodes
        sss->numlines = USHORT(mss->numsegs);
        sss->firstline = ULONG(mss->firstseg);
    }

    Z_Free(data);
}

void P_LoadNodes_DeePBSPV4(map_t *map)
{
    numnodes = (W_LumpLength(map->nodes) - 8) / sizeof(mapnode_deepbspv4_t);
    nodes = Z_Malloc(numnodes * sizeof(node_t), PU_LEVEL, 0);
    byte *data = W_CacheLumpNum(map->nodes, PU_STATIC);

    // [FG] skip header
    mapnode_deepbspv4_t *m = (mapnode_deepbspv4_t *)(data + 8);

    for (size_t i = 0; i < numnodes; i++)
    {
        node_t *no = &nodes[i];
        mapnode_deepbspv4_t *mn = &m[i];

        no->x = IntToFixed(SHORT(mn->x));
        no->y = IntToFixed(SHORT(mn->y));
        no->dx = IntToFixed(SHORT(mn->dx));
        no->dy = IntToFixed(SHORT(mn->dy));

        for (size_t j = 0; j < 2; j++)
        {
            // [MB] 2020-04-22: Fix endianess for DeePBSPV4 nodes
            no->children[j] = ULONG(mn->children[j]);

            for (size_t k = 0; k < 4; k++)
            {
                no->bbox[j][k] = IntToFixed(SHORT(mn->bbox[j][k]));
            }
        }
    }

    Z_Free(data);
}

// [FG] support maps with ZDBSP nodes

static void CheckOverflowZDBSP(int32_t *size, int32_t count)
{
    (*size) -= count;

    if ((*size) < 0)
    {
        I_Error("incorrectly built ZDBSP nodes");
    }
}

static void *DecompressZDBSP(map_t *map, byte **data, int32_t *length)
{
    // first estimate for compression rate:
    // output buffer size == 2.5 * input size
    int32_t outlen = 2.5 * (*length);
    byte *output = malloc(outlen);

    // initialize stream state for decompression
    z_stream zstream;
    memset(&zstream, 0, sizeof(zstream));
    zstream.next_in = *data;
    zstream.avail_in = *length;
    zstream.next_out = output;
    zstream.avail_out = outlen;

    if (inflateInit(&zstream) != Z_OK)
    {
        I_Error("Error during ZNOD nodes decompression initialization!");
    }

    // resize if output buffer runs full
    int err;
    while ((err = inflate(&zstream, Z_SYNC_FLUSH)) == Z_OK)
    {
        const int next_out_old = (int)(zstream.next_out - output);

        outlen *= 2;
        output = I_Realloc(output, outlen);
        zstream.next_out = output + next_out_old;
        zstream.avail_out = outlen - next_out_old;
    }

    if (err != Z_STREAM_END)
    {
        I_Error("Error during ZNOD nodes decompression!");
    }

    I_Printf(VB_DEBUG, "%s: ZNOD nodes compression ratio %.3f", __func__,
             (float)zstream.total_out / zstream.total_in);

    *data = output;
    *length = zstream.total_out;

    if (inflateEnd(&zstream) != Z_OK)
    {
        I_Error("Error during ZNOD nodes decompression shut-down!");
    }

    // release the original data lump
    W_CacheLumpNum(map->znodes, PU_CACHE);

    return output;
}

static void LoadSegs_XNOD(map_t *map, byte *data)
{
    for (size_t i = 0; i < numsegs; i++)
    {
        line_t *ldef;
        uint32_t linedef;
        uint8_t side;
        seg_t *li = &segs[i];
        mapseg_xnod_t *ml = (mapseg_xnod_t *)data + i;
        uint32_t v1, v2;

        v1 = LONG(ml->v1);
        v2 = LONG(ml->v2);
        li->v1 = &vertexes[v1];
        li->v2 = &vertexes[v2];

        linedef = USHORT(ml->linedef);
        // Andrey Budko: check for wrong indexes
        if (linedef >= numlines)
        {
            I_Error("seg %zu references a non-existent linedef %d", i, linedef);
        }

        ldef = &lines[linedef];
        li->linedef = ldef;
        side = ml->side;

        // Andrey Budko: fix wrong side index
        if (side != 0 && side != 1)
        {
            side = 1;
        }

        // Andrey Budko: check for wrong indexes
        if (ldef->sidenum[side] >= numsides)
        {
            I_Error(
                "linedef %d for seg %zu references a non-existent sidedef %d",
                linedef, i, ldef->sidenum[side]);
        }

        li->sidedef = &sides[ldef->sidenum[side]];

        /* cph 2006/09/30 - our frontsector can be the second side of the
         * linedef, so must check for NO_INDEX in case we are incorrectly
         * referencing the back of a 1S line */
        if (ldef->sidenum[side] != NO_INDEX)
        {
            li->frontsector = sides[ldef->sidenum[side]].sector;
        }
        else
        {
            li->frontsector = 0;
            I_Printf(VB_DEBUG, "%s: front of seg %zu has no sidedef\n",
                     __func__, i);
        }

        // seg angle and offset are not included
        li->angle = R_PointToAngle2(li->v1->x, li->v1->y, li->v2->x, li->v2->y);
        li->offset = P_GetOffset(li->v1, (ml->side ? ldef->v2 : ldef->v1));

        if (ldef->flags & ML_TWOSIDED && ldef->sidenum[side ^ 1] != NO_INDEX)
        {
            li->backsector = sides[ldef->sidenum[side ^ 1]].sector;
        }
        else
        {
            li->backsector = 0;
        }
    }
}

static void LoadSegs_XGL(map_t *map, byte *data)
{
    const mapseg_xgln_t *mln = (const mapseg_xgln_t *)data;
    const mapseg_xgl2_t *ml2 = (const mapseg_xgl2_t *)data;

    for (size_t i = 0; i < numsubsectors; ++i)
    {
        for (size_t j = 0; j < subsectors[i].numlines; ++j)
        {
            unsigned int v1;
            // unsigned int partner;
            unsigned int line;
            uint8_t side;
            seg_t *seg;

            if (map->bsp_format == BSP_XGLN || map->bsp_format == BSP_ZGLN)
            {
                v1 = LONG(mln->vertex);
                // partner = LONG(mln->partner);
                line = USHORT(mln->linedef);
                side = mln->side;
                FIX_NO_INDEX(line);
                mln++;
            }
            else
            {
                v1 = LONG(ml2->vertex);
                // partner = LONG(ml2->partner);
                line = ULONG(ml2->linedef);
                side = ml2->side;
                ml2++;
            }

            seg = &segs[subsectors[i].firstline + j];

            seg->v1 = &vertexes[v1];
            if (j == 0)
            {
                seg[subsectors[i].numlines - 1].v2 = seg->v1;
            }
            else
            {
                seg[-1].v2 = seg->v1;
            }

            if (line != NO_INDEX)
            {
                line_t *ldef;

                if (line >= numlines)
                {
                    I_Error("seg %zu, %zu references a non-existent linedef %d",
                            i, j, line);
                }

                ldef = &lines[line];
                seg->linedef = ldef;

                if (side != 0 && side != 1)
                {
                    I_Error("seg %zu, %zu references a non-existent side %d", i,
                            j, side);
                }

                if (ldef->sidenum[side] >= numsides)
                {
                    I_Error("linedef %d for seg %zu, %zu "
                            "references a non-existent sidedef %d",
                            line, i, j, ldef->sidenum[side]);
                }

                seg->sidedef = &sides[ldef->sidenum[side]];

                /* cph 2006/09/30 - our frontsector can be the second side of
                 * the linedef, so must check for NO_INDEX in case we are
                 * incorrectly referencing the back of a 1S line */
                if (ldef->sidenum[side] != NO_INDEX)
                {
                    seg->frontsector = sides[ldef->sidenum[side]].sector;
                }
                else
                {
                    seg->frontsector = 0;
                    I_Printf(VB_WARNING,
                             "%s: front of seg %zu, %zu has no sidedef",
                             __func__, i, j);
                }

                if (ldef->flags & ML_TWOSIDED
                    && (ldef->sidenum[side ^ 1] != NO_INDEX))
                {
                    seg->backsector = sides[ldef->sidenum[side ^ 1]].sector;
                }
                else
                {
                    seg->backsector = 0;
                }

                seg->offset =
                    P_GetOffset(seg->v1, (side ? ldef->v2 : ldef->v1));
            }
            else
            {
                seg->angle = 0;
                seg->offset = 0;
                seg->linedef = NULL;
                seg->sidedef = NULL;
                seg->frontsector = segs[subsectors[i].firstline].frontsector;
                seg->backsector = seg->frontsector;
            }
        }

        // Need all vertices to be defined before setting angles
        for (size_t j = 0; j < subsectors[i].numlines; ++j)
        {
            seg_t *seg = &segs[subsectors[i].firstline + j];

            if (seg->linedef)
            {
                seg->angle = R_PointToAngle2(seg->v1->x, seg->v1->y, seg->v2->x,
                                             seg->v2->y);
            }
        }
    }
}

void P_LoadBSPTree_ZDBSP(map_t *map)
{
    byte *data;
    byte *output = NULL;

    uint32_t orgVerts, newVerts;
    uint32_t numSubs, currSeg;
    uint32_t numSegs;
    uint32_t numNodes;
    vertex_t *newvertarray = NULL;

    uint32_t value;

    int32_t len = W_LumpLength(map->znodes);
    data = W_CacheLumpNum(map->znodes, PU_LEVEL);

    // char[4]
    CheckOverflowZDBSP(&len, 4);
    data += 4;

    bsp_format_t format = map->bsp_format;

    boolean compressed = format == BSP_ZNOD || format == BSP_ZGLN
                         || format == BSP_ZGL2 || format == BSP_ZGL3;

    int32_t version = (format == BSP_XGL3 || format == BSP_ZGL3)   ? 3
                      : (format == BSP_XGL2 || format == BSP_ZGL2) ? 2
                      : (format == BSP_XGLN || format == BSP_ZGLN) ? 1
                                                                   : 0;

    // 0. Uncompress nodes lump (or simply skip header)
    if (compressed)
    {
        output = DecompressZDBSP(map, &data, &len);
    }

    // 1. Load new vertices added during node building

    CheckOverflowZDBSP(&len, sizeof(orgVerts));
    memcpy(&value, data, sizeof(orgVerts));
    orgVerts = LONG(value);
    data += sizeof(orgVerts);

    CheckOverflowZDBSP(&len, sizeof(newVerts));
    memcpy(&value, data, sizeof(newVerts));
    newVerts = LONG(value);
    data += sizeof(newVerts);

    if (orgVerts + newVerts == numvertexes)
    {
        newvertarray = vertexes;
    }
    else
    {
        newvertarray =
            arena_alloc_num(world_arena, vertex_t, orgVerts + newVerts);
        memcpy(newvertarray, vertexes, orgVerts * sizeof(vertex_t));
        memset(newvertarray + orgVerts, 0, newVerts * sizeof(vertex_t));
    }

    CheckOverflowZDBSP(&len, newVerts * (sizeof(newvertarray[0].x) + sizeof(newvertarray[0].y)));
    for (size_t i = 0; i < newVerts; i++)
    {
        memcpy(&value, data, sizeof(newvertarray[0].x));
        newvertarray[i + orgVerts].r_x = newvertarray[i + orgVerts].x =
            LONG(value);
        data += sizeof(newvertarray[0].x);

        memcpy(&value, data, sizeof(newvertarray[0].y));
        newvertarray[i + orgVerts].r_y = newvertarray[i + orgVerts].y =
            LONG(value);
        data += sizeof(newvertarray[0].y);
    }

    if (vertexes != newvertarray)
    {
        for (size_t i = 0; i < numlines; i++)
        {
            line_t *line = &lines[i];
            line->v1 = line->v1 - vertexes + newvertarray;
            line->v2 = line->v2 - vertexes + newvertarray;
        }

        vertexes = newvertarray;
        numvertexes = orgVerts + newVerts;
    }

    // 2. Load subsectors

    CheckOverflowZDBSP(&len, sizeof(numSubs));
    memcpy(&value, data, sizeof(numSubs));
    numSubs = LONG(value);
    data += sizeof(numSubs);

    if (numSubs < 1)
    {
        I_Error("No subsectors in map!");
    }

    numsubsectors = numSubs;
    subsectors = arena_alloc_num(world_arena, subsector_t, numsubsectors);

    CheckOverflowZDBSP(&len, numSubs * sizeof(mapsubsector_xnod_t));
    for (size_t i = currSeg = 0; i < numsubsectors; i++)
    {
        subsector_t *sss = &subsectors[i];
        mapsubsector_xnod_t *mseg = (mapsubsector_xnod_t *)data + i;

        sss->firstline = currSeg;
        sss->numlines = ULONG(mseg->numsegs);
        currSeg += ULONG(mseg->numsegs);
    }

    data += numsubsectors * sizeof(mapsubsector_xnod_t);

    // 3. Load segs
    CheckOverflowZDBSP(&len, sizeof(numSegs));
    memcpy(&value, data, sizeof(numSegs));
    numSegs = ULONG(value);
    data += sizeof(numSegs);

    // The number of stored segs should match the number of segs used by
    // subsectors
    if (numSegs != currSeg)
    {
        I_Error("Incorrect number of segs in XNOD nodes!");
    }

    numsegs = numSegs;
    segs = arena_alloc_num(world_arena, seg_t, numsegs);

    switch (version)
    {
        case 0:
            CheckOverflowZDBSP(&len, numsegs * sizeof(mapseg_xnod_t));
            LoadSegs_XNOD(map, data);
            data += numsegs * sizeof(mapseg_xnod_t);
            break;
        case 1:
            CheckOverflowZDBSP(&len, numsegs * sizeof(mapseg_xgln_t));
            LoadSegs_XGL(map, data);
            data += numsegs * sizeof(mapseg_xgln_t);
            break;
        case 2:
        case 3:
            CheckOverflowZDBSP(&len, numsegs * sizeof(mapseg_xgl2_t));
            LoadSegs_XGL(map, data);
            data += numsegs * sizeof(mapseg_xgl2_t);
            break;
        default:
            I_Error("How did we get here?");
            break;
    }

    // 4. Load nodes
    CheckOverflowZDBSP(&len, sizeof(numNodes));
    memcpy(&value, data, sizeof(numNodes));
    numNodes = ULONG(value);
    data += sizeof(numNodes);

    numnodes = numNodes;
    nodes = Z_Malloc(numnodes * sizeof(node_t), PU_LEVEL, 0);

    size_t node_size =
        (version == 3) ? sizeof(mapnode_xgl3_t) : sizeof(mapnode_xnod_t);
    CheckOverflowZDBSP(&len, numNodes * node_size);

    for (size_t i = 0; i < numnodes; i++)
    {
        node_t *no = &nodes[i];

        if (version == 3)
        {
            const mapnode_xgl3_t *mn3 = (const mapnode_xgl3_t *)data + i;
            no->x = LONG(mn3->x);
            no->y = LONG(mn3->y);
            no->dx = LONG(mn3->dx);
            no->dy = LONG(mn3->dy);
            for (size_t j = 0; j < 2; j++)
            {
                no->children[j] = ULONG(mn3->children[j]);
                for (size_t k = 0; k < 4; k++)
                {
                    no->bbox[j][k] = IntToFixed(SHORT(mn3->bbox[j][k]));
                }
            }
        }
        else
        {
            const mapnode_xnod_t *mn = (const mapnode_xnod_t *)data + i;
            no->x = IntToFixed(SHORT(mn->x));
            no->y = IntToFixed(SHORT(mn->y));
            no->dx = IntToFixed(SHORT(mn->dx));
            no->dy = IntToFixed(SHORT(mn->dy));
            for (size_t j = 0; j < 2; j++)
            {
                no->children[j] = ULONG(mn->children[j]);
                for (size_t k = 0; k < 4; k++)
                {
                    no->bbox[j][k] = IntToFixed(SHORT(mn->bbox[j][k]));
                }
            }
        }
    }

    if (compressed && output)
    {
        free(output);
    }
    else
    {
        W_CacheLumpNum(map->znodes, PU_CACHE);
    }
}
